### ISSUE TITLE
Unable to run min-max attack on MNIST

### ISSUE THREAD

**Issue by SravB** [kohpangwei/data-poisoning-journal-release#1]
Hello,

I was trying to run min-max attack on MNIST and noticed based on the commands file noted below, one python script that seems to be missing is `run_general_attack.py` which also seems to be the only way to run the min-max attack on MNIST

https://github.com/kohpangwei/data-poisoning-journal-release/blob/master/commands 

Is there any workaround to run a min-max attack on MNIST? (Also I saw in the paper there were min-max attacks on general MNIST in addition to MNIST 17, is there a way to run attacks on both of these?)

**Comment by kohpangwei** [comment]
Ah, sorry, that's an old file; please use the file in the README (generateAttackFnc.m). Thanks!

**Comment by SravB** [comment]
I tried using the file (generateAttackFnc.m) as well but was having some difficulties (my Matlab version is 2016b). 

Do you have an example of min-max attack generation with generateAttackFnc.m?
